[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:cron]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
directory=/data/deephunter
command=cron -f
autorestart=true

[program:celery]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
directory=/data/deephunter
user        = celery                                   # User
group       = celery                                   # Group
numprocs    = 1                                      # Only one instance of the “multi” wrapper
autostart   = true
autorestart = true
startsecs   = 10
stopwaitsecs= 600                                    # Graceful shutdown timeout
priority    = 1000
killasgroup = true                                   # Kill the whole process group on stop
stopasgroup = true                                   # Send stop signal to the whole group
command=/data/venv/bin/celery -A deephunter worker --pidfile=/var/run/celery/celery.pid --logfile=/var/log/celery/celery.log --loglevel=INFO --time-limit=3600 --concurrency=3

[program:apache2]
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
directory=/data/deephunter
command=bash -c "rm -f /var/run/apache2/apache2.pid && exec /usr/sbin/apache2ctl -DFOREGROUND"
autorestart=true
stopasgroup=true
killasgroup=true
